# Generated by Django 4.1.1 on 2022-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_ingrediente_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoreceta',
            name='foto',
            field=models.FileField(upload_to='recetas/static/fotos'),
        ),
    ]
