# Generated by Django 4.1.1 on 2022-11-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_alter_fotoreceta_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoreceta',
            name='foto',
            field=models.FileField(upload_to='media/'),
        ),
    ]
