# Generated by Django 4.1.1 on 2022-11-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_alter_fotoreceta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='foto',
            field=models.FileField(default='media/fotos', upload_to='media/fotos'),
        ),
    ]
