# Generated by Django 4.1.1 on 2022-11-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_alter_receta_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='preparación',
            new_name='preparacion',
        ),
    ]
